steps:
- id: "build dev image"
  name: "gcr.io/cloud-builders/docker"
  args: ["build","--target", "development","-t", "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:dev-testing-${COMMIT_SHA}", "."]
- id: "push dev image"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:dev-testing-${COMMIT_SHA}"]
- id: "ruff"
  name: "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:dev-testing-${COMMIT_SHA}"
  args: ["ruff", "check", "src/","test/"]
- id: "mypy"
  name: "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:dev-testing-${COMMIT_SHA}"
  args: ["mypy", "--explicit-package-bases", "src", "test"]
- id: "run test case"
  name: "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:dev-testing-${COMMIT_SHA}"
  args: ["python", "-m", "unittest", "discover", "-s", "test/unit"]
- id: "build prod image"
  name: "gcr.io/cloud-builders/docker"
  args: ["build","--target", "production","-t", "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:production-${COMMIT_SHA}", "."]
- id: "push prod image"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:production-${COMMIT_SHA}"]
- id: "deploy to GKE"
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./k8s
  - image=asia-east1-docker.pkg.dev/${PROJECT_ID}/milecoolab/milecoolab-email-server:production-${COMMIT_SHA}
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

substitutions:
  _CLOUDSDK_COMPUTE_ZONE: 'asia-east1-a'
  _CLOUDSDK_CONTAINER_CLUSTER: 'email-server-cluster'
options:
  logging: CLOUD_LOGGING_ONLY
