apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "email-server-deployment"
  namespace: "my-email-server"
  labels:
    app: "email-server-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "email-server-deployment"
  template:
    metadata:
      labels:
        app: "email-server-deployment"
    spec:
      containers:
      - name: "milecoolab-email-server-sha256-1"
        image: "asia-east1-docker.pkg.dev/tw-rd-de-milecoolab-dev/milecoolab/milecoolab-email-server@sha256:7c3f088b3a98fc1a14cc03e26aa5bcac51cb084b11cc739431f20abfb75ac348"
        env: 
        - name: SMTP_SERVER
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: EMAIL_SENDER
          value: cm-contract@mile.cloud
        - name: GCP_PROJECT_ID
          value: tw-rd-de-milecoolab-dev
        - name: GCP_PUB_SUB_TOPIC_ID
          value: email-server-incoming
        - name: GCP_FIRESTORE_DATABASE_ID
          value: (default)
        - name: GCP_CLOUD_STORAGE_BUCKET_NAME
          value: tw-rd-de-milecoolab-dev_email-server
        - name: GCP_BIG_QUERY_VIEW
          value: tw-rd-de-milecoolab-dev.firestore_export.email_data_view
        - name: APP_PASSWORD
          valueFrom:
              secretKeyRef:
                name: my-secret
                key: app-password