apiVersion: "v1"
kind: "Service"
metadata:
  name: "email-server-deployment-service"
  namespace: "my-email-server"
  labels:
    app: "email-server-deployment"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
  selector:
    app: "email-server-deployment"
  type: "LoadBalancer"
  loadBalancerIP: ""
