apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "email-server-deployment"
  namespace: "my-email-server"
  labels:
    app: "email-server-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "email-server-deployment"
  template:
    metadata:
      labels:
        app: "email-server-deployment"
    spec:
      containers:
      - name: "milecoolab-email-server-sha256-1"
        image: "asia-east1-docker.pkg.dev/tw-rd-de-milecoolab-dev/milecoolab/milecoolab-email-server@sha256:7c3f088b3a98fc1a14cc03e26aa5bcac51cb084b11cc739431f20abfb75ac348"
